/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ValidatorsLazyImport = createFileRoute('/validators')()
const EpochLazyImport = createFileRoute('/epoch')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ValidatorsLazyRoute = ValidatorsLazyImport.update({
  id: '/validators',
  path: '/validators',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/validators.lazy').then((d) => d.Route))

const EpochLazyRoute = EpochLazyImport.update({
  id: '/epoch',
  path: '/epoch',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/epoch.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/epoch': {
      id: '/epoch'
      path: '/epoch'
      fullPath: '/epoch'
      preLoaderRoute: typeof EpochLazyImport
      parentRoute: typeof rootRoute
    }
    '/validators': {
      id: '/validators'
      path: '/validators'
      fullPath: '/validators'
      preLoaderRoute: typeof ValidatorsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/epoch': typeof EpochLazyRoute
  '/validators': typeof ValidatorsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/epoch': typeof EpochLazyRoute
  '/validators': typeof ValidatorsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/epoch': typeof EpochLazyRoute
  '/validators': typeof ValidatorsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/epoch' | '/validators'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/epoch' | '/validators'
  id: '__root__' | '/' | '/about' | '/epoch' | '/validators'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  EpochLazyRoute: typeof EpochLazyRoute
  ValidatorsLazyRoute: typeof ValidatorsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  EpochLazyRoute: EpochLazyRoute,
  ValidatorsLazyRoute: ValidatorsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/epoch",
        "/validators"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/epoch": {
      "filePath": "epoch.lazy.tsx"
    },
    "/validators": {
      "filePath": "validators.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
